"""Rename Group.description to Group.title

Revision ID: bc7b11b62a11
Revises: 112aa876bdbb
Create Date: 2026-08-07 20:17:30.882655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7b11b62a11'
down_revision: Union[str, Sequence[str], None] = '112aa876bdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'description', new_column_name='title', existing_type=sa.String(length=255))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'title', new_column_name='description', existing_type=sa.String(length=255))
    # ### end Alembic commands ###
